Added section "Installing Magento Extensions"
bitnami/bitnami-docker-magento pull request #220
Opened 2021-11-02 05:20 UTC by mcclede

**Description of the change**

Extends the README.md with the steps necessary to add an extension to the Bitnami Magento image.

**Benefits**

Adds information not currently in the document improving usability of the image especially for novice users.

**Possible drawbacks**

None

**Applicable issues**

#212 

**Additional information**

None

2021-11-02 14:56 UTC, migruiz4 requested changes
Hi @mcclede,

Thank you very much for your contribution! I have requested several changes, could you please have a look?

2021-11-02 14:56 UTC, migruiz4 commented on README.md
> +#### Step 1: Log into the container shall as root
There is a typo in this line:

```suggestion
#### Step 1: Log into the container shell as root
```

2021-11-02 14:56 UTC, migruiz4 commented on README.md
> +## Installing Magento Extensions
```suggestion
## Installing Magento extensions
```

2021-11-02 14:56 UTC, migruiz4 commented on README.md
> +$ php bin/magento cache:flush```
Fix typo and additional (```)
```suggestion
$ composer require <extension name>
$ php bin/magento module:enable <extension name>
$ php bin/magento setup:upgrade
$ php bin/magento setup:di:compile
$ php bin/magento setup:static-content:deploy -f
$ php bin/magento cache:flush
```

2021-11-05 01:02 UTC, mcclede commented on README.md
> +#### Step 1: Log into the container shall as root
Agree, fixed.

2021-11-05 01:02 UTC, mcclede commented on README.md
> +## Installing Magento Extensions
Agree, fixed.

2021-11-05 01:02 UTC, mcclede commented on README.md
> +$ php bin/magento cache:flush```
Agree, fixed

2021-11-08 13:34 UTC, merged