New functionality initialize store with sample data.
bitnami/bitnami-docker-magento pull request #237
Opened 2022-03-14 20:14 UTC by anggilb

**Description of the change**

Includes to the docker-compose.yml the ability to load sample data when we launch the container.

**Benefits**

It is usefull when you need to test extensions when you need sample data. 

**Possible drawbacks**

Incompatibility with the version ^2 of composer, but it is fixed.

**Applicable issues**

None

**Additional information**

Add your magento credentials and rename the file auth.json.sample to auth.json.

Thanks for share this repository, I needed to modify it for my personal use and I share with you my fields.

2022-03-15 09:36 UTC, marcosbc requested changes
Thanks for the great contribution! Please have a look at my comments.

In addition, it seems like pre-configuration may be needed via `auth.json`. If that is the case, would you also be able to add some instructions to the README?

2022-03-15 09:36 UTC, marcosbc commented on 2/debian-10/rootfs/opt/bitnami/scripts/magento-env.sh
> +export MAGENTO_INSTALL_SAMPLEDATA="${MAGENTO_INSTALL_SAMPLEDATA:-no}" # only used during the first initialization
Could you place this environment variable under the "Magento configuration" section? I think that it makes more sense there.

2022-03-15 09:36 UTC, marcosbc commented on 2/debian-10/rootfs/opt/bitnami/scripts/libmagento.sh
> +                info "Install Sample Data"
```suggestion
                info "Populating sample data"
```

2022-03-15 09:36 UTC, marcosbc commented on 2/debian-10/rootfs/opt/bitnami/scripts/libmagento.sh
> +                composer update --working-dir="$MAGENTO_BASE_DIR"
Are the `composer` commands actually required to populate the sample data? What happens if they are not updated? Maybe this could be avoided at any other step. My concern is that changing Composer configuration may give a lot of trouble, and Magento should be able to execute the command to deploy sample data before issues, using the existing configuration(s).

2022-03-15 09:36 UTC, marcosbc commented on 2/debian-10/rootfs/opt/bitnami/scripts/libmagento.sh
> +                magento_execute setup:upgrade
Is there any reason for `setup:upgrade` being required for populating sample data? My understanding is that it should not be needed.

2022-03-15 09:36 UTC, marcosbc commented on 2/debian-10/Dockerfile
> +
If possible, we should add it directly into `rootfs` and avoid using `COPY` here.

In addition, I see that `auth.json.sample` is the filename added to the repo, not `auth.json`. If it still works that way, is `auth.json` even needed?

If it is needed, then I'm assuming that credentials need to be set. Wouldn't it make more sense for users to have to mount the file at runtime? We can always add a validation in `magento_validate` to ensure the file exists if `MAGENTO_INSTALL_SAMPLEDATA` is enabled.

2022-03-15 09:51 UTC, anggilb commented on 2/debian-10/rootfs/opt/bitnami/scripts/magento-env.sh
> +export MAGENTO_INSTALL_SAMPLEDATA="${MAGENTO_INSTALL_SAMPLEDATA:-no}" # only used during the first initialization
Yes, it have sense.

2022-03-15 09:51 UTC, anggilb commented on 2/debian-10/rootfs/opt/bitnami/scripts/libmagento.sh
> +                info "Install Sample Data"
For me it is OK.

2022-03-15 09:58 UTC, anggilb commented on 2/debian-10/rootfs/opt/bitnami/scripts/libmagento.sh
> +                magento_execute setup:upgrade
In all the tutorials I see sampledata:deploy (it install some extensions) and after that setup:upgrade, I am not sure what happens if the skip the last command, but I suppose that it doesn't work. I've revised that after this change, setup:update doesn't be executed.

2022-03-15 09:59 UTC, anggilb commented on 2/debian-10/Dockerfile
> +
Yes, `auth.json.sample` is a way to force to the user to include their credentials to download the module, I am not sure if it is the best way, but in a rootfs folder it is more difficult to see it. But I will implement that you prefer.

2022-03-16 16:21 UTC, marcosbc requested changes

2022-04-07 01:33 UTC, closed without merging